// <auto-generated />
using System;
using Capa.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capa.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260205074100_InicioDb")]
    partial class InicioDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capa.Shared.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Cuestionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Cuestionarios");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroCi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadEducativaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NroCi")
                        .IsUnique();

                    b.HasIndex("UnidadEducativaId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Capa.Shared.Entities.IntentoTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("IntentosTest");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Recomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Puntuacion")
                        .HasColumnType("real");

                    b.Property<int>("ResultadoIAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ResultadoIAId");

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Respuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntentoTestId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntentoTestId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");
                });

            modelBuilder.Entity("Capa.Shared.Entities.ResultadoIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentoTestId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntentoTestId")
                        .IsUnique();

                    b.ToTable("ResultadosIA");
                });

            modelBuilder.Entity("Capa.Shared.Entities.UnidadEducativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroContacto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UnidadEducativas");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.HasOne("Capa.Shared.Entities.UnidadEducativa", "UnidadEducativa")
                        .WithMany("Estudiantes")
                        .HasForeignKey("UnidadEducativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadEducativa");
                });

            modelBuilder.Entity("Capa.Shared.Entities.IntentoTest", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Estudiante", "Estudiante")
                        .WithMany("IntentosTest")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Pregunta", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Cuestionario", "Cuestionario")
                        .WithMany("Preguntas")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Recomendacion", b =>
                {
                    b.HasOne("Capa.Shared.Entities.Carrera", "Carrera")
                        .WithMany("Recomendaciones")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capa.Shared.Entities.ResultadoIA", "ResultadoIA")
                        .WithMany("Recomendaciones")
                        .HasForeignKey("ResultadoIAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("ResultadoIA");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Respuesta", b =>
                {
                    b.HasOne("Capa.Shared.Entities.IntentoTest", "IntentoTest")
                        .WithMany("Respuestas")
                        .HasForeignKey("IntentoTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capa.Shared.Entities.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntentoTest");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Capa.Shared.Entities.ResultadoIA", b =>
                {
                    b.HasOne("Capa.Shared.Entities.IntentoTest", "IntentoTest")
                        .WithOne("ResultadoIA")
                        .HasForeignKey("Capa.Shared.Entities.ResultadoIA", "IntentoTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntentoTest");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Carrera", b =>
                {
                    b.Navigation("Recomendaciones");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Cuestionario", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Estudiante", b =>
                {
                    b.Navigation("IntentosTest");
                });

            modelBuilder.Entity("Capa.Shared.Entities.IntentoTest", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("ResultadoIA");
                });

            modelBuilder.Entity("Capa.Shared.Entities.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Capa.Shared.Entities.ResultadoIA", b =>
                {
                    b.Navigation("Recomendaciones");
                });

            modelBuilder.Entity("Capa.Shared.Entities.UnidadEducativa", b =>
                {
                    b.Navigation("Estudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
